#!/bin/bash -e
# set ipconfig

. /etc/default/inithooks

fatal() { echo "FATAL: $@" >&2; exit 1; }
check_state() {
    iface_l=$(ip a | grep " $1: ")
    echo "$iface_l" | sed -En "s|^.*state ([A-Z]+ ).*|\1|p"
}

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
INTERACTIVE_WIFI="${INTERACTIVE_WIFI,,}"
if [[ "$INTERACTIVE_WIFI" == "true"  ]]; then
    if [[ "$(check_state wlan0)" =~ [A-Z]+  ]]; then
        INTERFACE=wlan0
        $INITHOOKS_PATH/bin/wpa_pass.py
    fi
elif [[ -n "$IP_CONFIG" ]]; then
    if [[ "$INTERFACE" == 'wlan0' ]]; then
        if [[ -z "$WPA_SSID" ]] || [[ -z "$WPA_PASS" ]];
            fatal "wlan0 requires SSID & password."
        fi
        $INITHOOKS_PATH/bin/wpa_pass.py --ssid="$WPA_SSID" --pass="$WPA_PASS"
    elif [[ "$(check_state eth0)" =~ [A-Z]+ ]]; then
        INTERFACE=eth0
    else
        fatal "IP_CONFIG set but no interface found."
    fi
else
    exit 0
fi
[ ! -e /etc/network/interfaces ] && fatal "Interfaces file not found."

case $INTERFACE in
    eth0)
        # if IP_CONFIG unchanged skip this script & avoid iface reconfig
        grep -q "iface eth0 inet $IP_CONFIG" /etc/network/interfaces \
            && exit 0;
    wlan0)
        continue;;
    *)
        fatal "Only eth0 or wlan0 can be pre-configured (not $interface)"
esac

case $IPCONFIG in
    manual|dhcp)
        confconsole-ip-conf $INTERFACE --set="$IPCONFIG"
    static)
        if [[ -z "$IP_ADDRESS" ]] || [[ -z "$IP_NETMASK" ]] \\
                || [[ -z "$IP_GW" ]] || [[ -z "$IP_DNS1"]]; then
            fatal "static ip needs addr, netmask, gateway & dns."
        fi;
        confconsole-ip-conf $INTERFACE \
            --ip="$IP_ADDRESS" --netm="$IP_NETMASK" \
            --gatew="$IP_GW" --dns="$IP_DNS1" --dns="$IP_DNS2";;
    *)
        fatal "Unrecognised IPCONFIG ($IPCONFIG)";;
esac

ip link set $interface down
ifup --exclude=lo -a

exit $?
