#!/bin/bash -e
# remove existing ssh keys and generate new ones
# note: ssh daemon needs to be restarted for changes to take effect

[ -n "$_TURNKEY_INIT" ] && exit 0

echo "* Regenerating SSH cryptographic keys"

systemctl is-active --quiet ssh.service && systemctl stop ssh.service

rm -f /etc/ssh/*_key{,.pub}
dpkg-reconfigure --frontend=noninteractive --no-reload openssh-server

systemctl is-active --quiet ssh.service || systemctl start ssh.service

